version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
    image: ${AWS_ECR_REPOSITORY:-web}:${IMAGE_TAG:-latest}
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
