---
name: workflow

on:
  push:
    branches:
      - main
      - feature/*
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Image
        run: docker-compose build
      -
        name: Integration Test
        run: docker-compose run --entrypoint "pytest -v -s" web
  cd:
    name: Deployment
    runs-on: ubuntu-latest
    needs:
      - ci
    #if: startsWith(github.ref, 'refs/tags/')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - 
        name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - 
        name: Build and Push to AWS ECR
        env:
          AWS_ECR_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: latest
        run: |
          docker-compose build
          docker-compose push
